version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "jthegedus"
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
    reviewers:
      - "jthegedus"
